wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721231163
    t:
      1:
      - 1
      - 41
      - 46
      - 55
      2:
      - 1
      - 41
      - 46
      - 55
      3:
      - 1
      - 17
      - 23
      - 37
      - 61
      4: 3.8.19
      5: 0.17.4
      8:
      - 1
      - 5
      13: linux-x86_64
