name: speml24_3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - pip
  - protobuf<3.21
  - pip:
    - syft==0.2.9
    - torchvision==0.5.0
    - ipykernel==5.5.6