name: base
channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- pandas
- numpy=1.18.5
- matplotlib
- pip<24.1
- wandb
- protobuf<3.21
- python-dotenv
- pip:
  - syft==0.2.9
  - torchvision==0.5.0
  - ipykernel==5.5.6
