FROM mcr.microsoft.com/devcontainers/python:3.8

# Copy the environment.yml file into the container
# COPY environment.yml /tmp/environment.yml

# Create the conda environment
# RUN mamba env create -f /tmp/environment.yml

ENV DISPLAY=:0